//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_datos
    {
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
    }
}
